"""empty message

Revision ID: 508ff5b596aa
Revises: cdaa2c8a88e6
Create Date: 2017-01-27 14:01:47.537631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508ff5b596aa'
down_revision = 'cdaa2c8a88e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
