"""changed user model

Revision ID: 554760bb71f1
Revises: fa435ff30bc4
Create Date: 2017-01-26 12:17:41.209515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554760bb71f1'
down_revision = 'fa435ff30bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('active')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('confirmed_at', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'password_hash')
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
