"""empty message

Revision ID: 829465d60d89
Revises: c843467d66e6
Create Date: 2017-01-26 14:20:02.771647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829465d60d89'
down_revision = 'c843467d66e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    # ### end Alembic commands ###
