"""confirmation

Revision ID: c843467d66e6
Revises: cbd954e6ab1e
Create Date: 2017-01-26 12:38:39.791510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c843467d66e6'
down_revision = 'cbd954e6ab1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
