"""empty message

Revision ID: fb0311ff02e4
Revises: 829465d60d89
Create Date: 2017-01-26 14:22:42.943504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0311ff02e4'
down_revision = '829465d60d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'member_since')
    # ### end Alembic commands ###
